// Generated index.html for displaying page content and "Add Comment" functionality

#pragma once

static char *PAGE_INDEX =
    "<!-- Post page for towertalk -->\n"
    "<!DOCTYPE html>\n"
    "<html>\n"
    "    <body>\n"
    "        <!-- Content -->\n"
    "        <h1 id = 'post-title'> Post </h1>\n"
    "        <github-md id = 'post-body'> Body </github-md>\n"
    "        <h1> Comments </h1>\n"
    "        <ul id = 'comment-list'> </ul>\n"
    "\n"
    "        <script\n"
    "src = 'https://cdn.jsdelivr.net/gh/MarketingPipeline/Markdown-Tag/markdown-tag-GitHub.js'\n"
    "        ></script>\n"
    "\n"
    "        <!-- Pull content and handle submission and what not -->\n"
    "        <script>\n"
    "            // Get info about the current user and post\n"
    "            const path = window.location.pathname;\n"
    "            const match = path.match(/^\\/~([^/]+)\\/towertalk\\/posts\\/([0-9]+)/);\n"
    "            const username = match ? match[1] : '<user>';\n"
    "            const post_id = match ? parseInt(match[2]) : -1;\n"
    "\n"
    "            // Retrieve the post title and body\n"
    "            fetch(\n"
    "        `https://moontowercomputer.club/~${username}/towertalk/posts/${post_id}/TITLE.txt`\n"
    "            ).then(response => {\n"
    "                if (response.status == 200) {\n"
    "                    return response.text();\n"
    "                } else {\n"
    "                    return '<title>';\n"
    "                }\n"
    "            }).then(title => {\n"
    "                document.getElementById('post-title').textContent =\n"
    "                    `Post by ${username} - ${title}`;\n"
    "                document.title = `Tower Talk Post by ${username} - ${title}`;\n"
    "            });\n"
    "            fetch(\n"
    "        `https://moontowercomputer.club/~${username}/towertalk/posts/${post_id}/BODY.md`\n"
    "            ).then(response => {\n"
    "                if (response.status == 200) {\n"
    "                    return response.text();\n"
    "                } else {\n"
    "                    return '<title>';\n"
    "                }\n"
    "            }).then(body => {\n"
    "                // TODO: Support Markdown\n"
    "                document.getElementById('post-body').textContent = body;\n"
    "                renderMarkdown();\n"
    "            });\n"
    "\n"
    "            // Pull the comments from all users' cgi-bins for this user's post\n"
    "            fetch(\n"
    "                `https://moontowercomputer.club/~${username}/cgi-bin/towertalk.bin`,\n"
    "                {\n"
    "                    method: 'POST',\n"
    "                    headers: {\n"
    "                        'Content-Type': 'text/plain'\n"
    "                    },\n"
    "                    body: '3'\n"
    "                }\n"
    "            ).then(response => response.json())\n"
    "            .then(async users => {\n"
    "                let comment_promises = users.map(user =>\n"
    "                    fetch(\n"
    "                        `https://moontowercomputer.club/~${username}/cgi-bin/towertalk.bin`,\n"
    "                        {\n"
    "                            method: 'POST',\n"
    "                            headers: {\n"
    "                                'Content-Type': 'text/plain'\n"
    "                            },\n"
    "                            body: `4{${user}}{${username}}{${post_id}}`\n"
    "                         }\n"
    "                    ).then(response => {\n"
    "                        if (response.status == 200) {\n"
    "                            return response.json();\n"
    "                        } else {\n"
    "                            return []\n"
    "                        }\n"
    "                    }).then(user_comms => {\n"
    "                        return user_comms.map(com => {\n"
    "                            com['user'] = user;\n"
    "                            return com;\n"
    "                        });\n"
    "                    })\n"
    "                );\n"
    "                let nested = await Promise.all(comment_promises);\n"
    "                let comments = nested.flat();\n"
    "                comments.sort((a, b) => a['index'] - b['index']);\n"
    "                let comment_ls = document.getElementById('comment-list');\n"
    "                for (const comment of comments) {\n"
    "                    let comment_li = document.createElement('li');\n"
    "                    comment_li.textContent = `${comment['user']} says`\n"
    "                    let comment_md = document.createElement('github-md');\n"
    "                    comment_md.textContent = comment['body'];\n"
    "                    comment_li.appendChild(comment_md);\n"
    "                    comment_ls.appendChild(comment_li);\n"
    "                    renderMarkdown();\n"
    "                }\n"
    "            })\n"
    "        </script>\n"
    "    </body>\n"
    "</html>\n";
